insert into bookmodule_book (ID, Title, Author, Price, Edition) values (1, 'Whispers in the Wind', 'Jessica Miller', 4685.511, 6.2);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (2, 'Midnight Moonlight', 'Emily Johnson', 2475.8163, 4.12);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (3, 'Enchanted Forest', 'Emily Johnson', 2111.9549, 7.98);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (4, 'Midnight Moonlight', 'Sarah Wilson', 4020.3023, 1.98);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (5, 'Echoes of Eternity', 'Michael Brown', 1995.0681, 3.53);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (6, 'Eternal Embrace', 'Amanda White', 4318.6381, 6.85);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (7, 'Mystic Dreams', 'Kevin Davis', 4073.9367, 8.56);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (8, 'Eternal Embrace', 'Jessica Miller', 3802.5941, 4.48);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (9, 'Dancing Shadows', 'John Smith', 2392.9855, 9.56);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (10, 'Eternal Embrace', 'John Smith', 3176.2952, 9.71);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (11, 'Eternal Embrace', 'Michael Brown', 3061.4253, 1.49);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (12, 'Echoes of Eternity', 'John Smith', 1093.7302, 7.17);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (13, 'Dancing Shadows', 'David Lee', 3888.6747, 6.82);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (14, 'Dancing Shadows', 'Kevin Davis', 3149.1598, 8.63);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (15, 'Whispers in the Wind', 'Michael Brown', 3870.9931, 2.72);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (16, 'Starlight Serenade', 'David Lee', 2118.2973, 2.87);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (17, 'Whispers in the Wind', 'David Lee', 3775.3534, 8.37);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (18, 'Midnight Moonlight', 'Brian Taylor', 4565.1035, 1.3);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (19, 'Starlight Serenade', 'Brian Taylor', 216.4256, 3.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (20, 'Twilight Symphony', 'Kevin Davis', 3659.4615, 7.66);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (21, 'Mystic Dreams', 'Amanda White', 158.339, 7.85);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (22, 'Starlight Serenade', 'Amanda White', 4829.3236, 6.68);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (23, 'Eternal Embrace', 'Sarah Wilson', 3679.8512, 4.38);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (24, 'Midnight Moonlight', 'Jessica Miller', 4649.1489, 9.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (25, 'Echoes of Eternity', 'Jessica Miller', 1140.1819, 3.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (26, 'Dancing Shadows', 'John Smith', 3335.4434, 6.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (27, 'Enchanted Forest', 'John Smith', 4311.0558, 1.03);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (28, 'Mystic Dreams', 'Emily Johnson', 265.4235, 9.14);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (29, 'Mystic Dreams', 'Kevin Davis', 424.2989, 8.88);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (30, 'Twilight Symphony', 'Amanda White', 712.9838, 4.82);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (31, 'Mystic Dreams', 'David Lee', 47.1306, 3.38);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (32, 'Mystic Dreams', 'John Smith', 1616.0151, 2.44);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (33, 'The Secret Garden', 'Kevin Davis', 2498.5198, 8.27);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (34, 'Starlight Serenade', 'Olivia Martinez', 4744.4257, 3.83);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (35, 'The Secret Garden', 'Brian Taylor', 3253.0119, 9.33);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (36, 'Mystic Dreams', 'Kevin Davis', 2588.931, 1.01);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (37, 'Echoes of Eternity', 'David Lee', 2592.0438, 7.48);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (38, 'Enchanted Forest', 'Emily Johnson', 1662.7368, 1.7);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (39, 'Mystic Dreams', 'Jessica Miller', 4661.8356, 8.82);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (40, 'Starlight Serenade', 'Michael Brown', 4172.0281, 9.87);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (41, 'Enchanted Forest', 'Sarah Wilson', 93.5043, 9.82);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (42, 'Eternal Embrace', 'Olivia Martinez', 2593.8997, 2.99);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (43, 'Enchanted Forest', 'Michael Brown', 4313.9259, 9.39);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (44, 'Starlight Serenade', 'Michael Brown', 3817.1204, 8.93);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (45, 'Whispers in the Wind', 'John Smith', 1844.0777, 5.66);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (46, 'Mystic Dreams', 'Amanda White', 2796.4323, 9.14);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (47, 'Midnight Moonlight', 'Jessica Miller', 3956.2331, 2.5);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (48, 'Dancing Shadows', 'Sarah Wilson', 3678.1123, 5.05);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (49, 'The Secret Garden', 'Kevin Davis', 3090.5035, 4.22);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (50, 'Echoes of Eternity', 'Olivia Martinez', 1032.0224, 2.06);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (51, 'Dancing Shadows', 'Kevin Davis', 1700.7926, 5.03);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (52, 'Whispers in the Wind', 'Kevin Davis', 3981.4001, 9.42);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (53, 'Eternal Embrace', 'John Smith', 248.8359, 4.31);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (54, 'Dancing Shadows', 'Amanda White', 131.0755, 7.66);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (55, 'Dancing Shadows', 'Amanda White', 313.3788, 5.46);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (56, 'Midnight Moonlight', 'Amanda White', 4536.2124, 2.42);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (57, 'Midnight Moonlight', 'Jessica Miller', 4312.5507, 5.75);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (58, 'Enchanted Forest', 'Amanda White', 1626.2632, 3.92);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (59, 'The Secret Garden', 'Brian Taylor', 2669.3863, 6.48);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (60, 'Whispers in the Wind', 'Brian Taylor', 2271.7781, 8.96);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (61, 'Starlight Serenade', 'Kevin Davis', 3436.5144, 9.21);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (62, 'Twilight Symphony', 'Jessica Miller', 3752.828, 8.19);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (63, 'Mystic Dreams', 'Michael Brown', 4150.2696, 6.12);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (64, 'Enchanted Forest', 'Michael Brown', 2092.187, 8.33);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (65, 'Dancing Shadows', 'Amanda White', 877.4211, 2.68);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (66, 'Eternal Embrace', 'John Smith', 4281.9886, 9.52);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (67, 'Mystic Dreams', 'Emily Johnson', 2489.1224, 3.94);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (68, 'The Secret Garden', 'Sarah Wilson', 1249.2688, 7.95);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (69, 'The Secret Garden', 'Sarah Wilson', 3536.0799, 3.65);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (70, 'Echoes of Eternity', 'Olivia Martinez', 2381.0334, 8.66);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (71, 'Twilight Symphony', 'Brian Taylor', 2344.1272, 7.57);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (72, 'Dancing Shadows', 'Jessica Miller', 4008.244, 4.57);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (73, 'Midnight Moonlight', 'Amanda White', 346.7834, 9.47);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (74, 'Starlight Serenade', 'Kevin Davis', 2869.6682, 4.58);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (75, 'Whispers in the Wind', 'Brian Taylor', 1123.7599, 7.93);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (76, 'Echoes of Eternity', 'Brian Taylor', 1725.9608, 8.64);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (77, 'Starlight Serenade', 'John Smith', 1167.2378, 3.41);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (78, 'Dancing Shadows', 'Emily Johnson', 3988.1829, 1.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (79, 'Midnight Moonlight', 'Olivia Martinez', 1476.2981, 4.92);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (80, 'Echoes of Eternity', 'Sarah Wilson', 3647.6356, 8.44);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (81, 'Enchanted Forest', 'Emily Johnson', 4899.2421, 5.55);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (82, 'Starlight Serenade', 'Michael Brown', 399.6222, 7.38);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (83, 'Dancing Shadows', 'Michael Brown', 3975.6834, 3.07);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (84, 'Enchanted Forest', 'Amanda White', 4924.6289, 3.16);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (85, 'Enchanted Forest', 'Amanda White', 306.014, 9.53);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (86, 'Mystic Dreams', 'Olivia Martinez', 962.9728, 2.75);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (87, 'Dancing Shadows', 'Olivia Martinez', 1731.6709, 9.93);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (88, 'The Secret Garden', 'Emily Johnson', 3480.5048, 2.74);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (89, 'Dancing Shadows', 'Amanda White', 4509.4959, 1.91);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (90, 'Dancing Shadows', 'David Lee', 1450.1744, 8.39);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (91, 'Whispers in the Wind', 'David Lee', 1278.5392, 1.74);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (92, 'Echoes of Eternity', 'Amanda White', 2429.1236, 1.62);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (93, 'Eternal Embrace', 'John Smith', 3059.6967, 8.91);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (94, 'Whispers in the Wind', 'Emily Johnson', 2384.8748, 1.54);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (95, 'The Secret Garden', 'Jessica Miller', 2851.5551, 9.4);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (96, 'Dancing Shadows', 'David Lee', 3122.3202, 8.76);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (97, 'Enchanted Forest', 'Jessica Miller', 3930.7321, 9.51);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (98, 'Dancing Shadows', 'Brian Taylor', 4240.1506, 6.86);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (99, 'Starlight Serenade', 'John Smith', 2885.7946, 8.19);
insert into bookmodule_book (ID, Title, Author, Price, Edition) values (100, 'Eternal Embrace', 'John Smith', 3555.4657, 7.78);
