insert into bookmodule_book (id, title, author, price, edition) values (1, 'Enchanted Dreams', 'Sarah Thompson', '$6.25', 5);
insert into bookmodule_book (id, title, author, price, edition) values (2, 'Enchanted Dreams', 'Sarah Thompson', '$15.25', 8);
insert into bookmodule_book (id, title, author, price, edition) values (3, 'Emerald Enchantment', 'Michael Davis', '$5.75', 2);
insert into bookmodule_book (id, title, author, price, edition) values (4, 'The Secret Garden', 'Kevin Brown', '$9.99', 6);
insert into bookmodule_book (id, title, author, price, edition) values (5, 'Whispers in the Wind', 'Emily Johnson', '$8.75', 2);
insert into bookmodule_book (id, title, author, price, edition) values (6, 'Whispers in the Wind', 'David Wilson', '$15.25', 1);
insert into bookmodule_book (id, title, author, price, edition) values (7, 'Whispers in the Wind', 'David Wilson', '$8.75', 2);
insert into bookmodule_book (id, title, author, price, edition) values (8, 'Starlight Serenade', 'Sarah Thompson', '$6.25', 4);
insert into bookmodule_book (id, title, author, price, edition) values (9, 'Whispers in the Wind', 'Michael Davis', '$14.99', 4);
insert into bookmodule_book (id, title, author, price, edition) values (10, 'Midnight Moonlight', 'Jessica Lee', '$9.99', 2);
