insert into bookmodule_student (id, name, age, address) values (1, 'John Smith', 47, 'Pinecrest');
insert into bookmodule_student (id, name, age, address) values (2, 'Sarah Thompson', 25, 'Springfield');
insert into bookmodule_student (id, name, age, address) values (3, 'Jessica Martinez', 47, 'Rivertown');
insert into bookmodule_student (id, name, age, address) values (4, 'Michael Davis', 25, 'Lakeview');
insert into bookmodule_student (id, name, age, address) values (5, 'Kevin Lee', 27, 'Springfield');
insert into bookmodule_student (id, name, age, address) values (6, 'Amanda Garcia', 50, 'Willow Creek');
insert into bookmodule_student (id, name, age, address) values (7, 'Kevin Lee', 21, 'Harbor City');
insert into bookmodule_student (id, name, age, address) values (8, 'Sarah Thompson', 42, 'Rivertown');
insert into bookmodule_student (id, name, age, address) values (9, 'Michael Davis', 21, 'Willow Creek');
insert into bookmodule_student (id, name, age, address) values (10, 'Michael Davis', 25, 'Sunset Valley');
